// Code generated by Kitex v0.9.0. DO NOT EDIT.

package agentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	agent "agent/kitex_gen/agent"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, Req *agent.PingRequest, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	UpdateConfig(ctx context.Context, Req *agent.PingRequest, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentServiceClient struct {
	*kClient
}

func (p *kAgentServiceClient) Ping(ctx context.Context, Req *agent.PingRequest, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, Req)
}

func (p *kAgentServiceClient) UpdateConfig(ctx context.Context, Req *agent.PingRequest, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateConfig(ctx, Req)
}
