// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_level.proto

package alert_level

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LevelName string `protobuf:"bytes,1,opt,name=levelName,proto3" json:"levelName" form:"levelName" query:"levelName"`
	Color     string `protobuf:"bytes,2,opt,name=color,proto3" json:"color" form:"color" query:"color"`
	LevelDesc string `protobuf:"bytes,3,opt,name=levelDesc,proto3" json:"levelDesc" form:"levelDesc" query:"levelDesc"`
}

func (x *LevelRequest) Reset() {
	*x = LevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_level_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelRequest) ProtoMessage() {}

func (x *LevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_level_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelRequest.ProtoReflect.Descriptor instead.
func (*LevelRequest) Descriptor() ([]byte, []int) {
	return file_alert_level_proto_rawDescGZIP(), []int{0}
}

func (x *LevelRequest) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *LevelRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LevelRequest) GetLevelDesc() string {
	if x != nil {
		return x.LevelDesc
	}
	return ""
}

var File_alert_level_proto protoreflect.FileDescriptor

var file_alert_level_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x60, 0x0a, 0x0c, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x42, 0x1d, 0x5a, 0x1b,
	0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_alert_level_proto_rawDescOnce sync.Once
	file_alert_level_proto_rawDescData = file_alert_level_proto_rawDesc
)

func file_alert_level_proto_rawDescGZIP() []byte {
	file_alert_level_proto_rawDescOnce.Do(func() {
		file_alert_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_level_proto_rawDescData)
	})
	return file_alert_level_proto_rawDescData
}

var file_alert_level_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alert_level_proto_goTypes = []interface{}{
	(*LevelRequest)(nil), // 0: alert.LevelRequest
}
var file_alert_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_level_proto_init() }
func file_alert_level_proto_init() {
	if File_alert_level_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_level_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_level_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_level_proto_goTypes,
		DependencyIndexes: file_alert_level_proto_depIdxs,
		MessageInfos:      file_alert_level_proto_msgTypes,
	}.Build()
	File_alert_level_proto = out.File
	file_alert_level_proto_rawDesc = nil
	file_alert_level_proto_goTypes = nil
	file_alert_level_proto_depIdxs = nil
}
