// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_restrain.proto

package alert_restrain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestrainType   string   `protobuf:"bytes,1,opt,name=restrainType,proto3" json:"restrainType" form:"restrainType" query:"restrainType"`
	Fields         []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields" form:"fields" query:"fields"`
	CumulativeTime int64    `protobuf:"varint,3,opt,name=cumulativeTime,proto3" json:"cumulativeTime" form:"cumulativeTime" query:"cumulativeTime"`
}

func (x *RestrainRequest) Reset() {
	*x = RestrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_restrain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestrainRequest) ProtoMessage() {}

func (x *RestrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_restrain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestrainRequest.ProtoReflect.Descriptor instead.
func (*RestrainRequest) Descriptor() ([]byte, []int) {
	return file_alert_restrain_proto_rawDescGZIP(), []int{0}
}

func (x *RestrainRequest) GetRestrainType() string {
	if x != nil {
		return x.RestrainType
	}
	return ""
}

func (x *RestrainRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RestrainRequest) GetCumulativeTime() int64 {
	if x != nil {
		return x.CumulativeTime
	}
	return 0
}

var File_alert_restrain_proto protoreflect.FileDescriptor

var file_alert_restrain_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x75, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x0e,
	0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65,
	0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_restrain_proto_rawDescOnce sync.Once
	file_alert_restrain_proto_rawDescData = file_alert_restrain_proto_rawDesc
)

func file_alert_restrain_proto_rawDescGZIP() []byte {
	file_alert_restrain_proto_rawDescOnce.Do(func() {
		file_alert_restrain_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_restrain_proto_rawDescData)
	})
	return file_alert_restrain_proto_rawDescData
}

var file_alert_restrain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alert_restrain_proto_goTypes = []interface{}{
	(*RestrainRequest)(nil), // 0: alert.RestrainRequest
}
var file_alert_restrain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_restrain_proto_init() }
func file_alert_restrain_proto_init() {
	if File_alert_restrain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_restrain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_restrain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_restrain_proto_goTypes,
		DependencyIndexes: file_alert_restrain_proto_depIdxs,
		MessageInfos:      file_alert_restrain_proto_msgTypes,
	}.Build()
	File_alert_restrain_proto = out.File
	file_alert_restrain_proto_rawDesc = nil
	file_alert_restrain_proto_goTypes = nil
	file_alert_restrain_proto_depIdxs = nil
}
