// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_channel.proto

package alert_channel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName  string `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName" form:"channelName" query:"channelName"`
	ChannelType  string `protobuf:"bytes,2,opt,name=channelType,proto3" json:"channelType" form:"channelType" query:"channelType"`
	ChannelSign  string `protobuf:"bytes,3,opt,name=channelSign,proto3" json:"channelSign" form:"channelSign" query:"channelSign"`
	ChannelGroup string `protobuf:"bytes,4,opt,name=channelGroup,proto3" json:"channelGroup" form:"channelGroup" query:"channelGroup"`
}

func (x *AlertChannelRequest) Reset() {
	*x = AlertChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertChannelRequest) ProtoMessage() {}

func (x *AlertChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertChannelRequest.ProtoReflect.Descriptor instead.
func (*AlertChannelRequest) Descriptor() ([]byte, []int) {
	return file_alert_channel_proto_rawDescGZIP(), []int{0}
}

func (x *AlertChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *AlertChannelRequest) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *AlertChannelRequest) GetChannelSign() string {
	if x != nil {
		return x.ChannelSign
	}
	return ""
}

func (x *AlertChannelRequest) GetChannelGroup() string {
	if x != nil {
		return x.ChannelGroup
	}
	return ""
}

var File_alert_channel_proto protoreflect.FileDescriptor

var file_alert_channel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x9f, 0x01, 0x0a,
	0x13, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x1f,
	0x5a, 0x1d, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_channel_proto_rawDescOnce sync.Once
	file_alert_channel_proto_rawDescData = file_alert_channel_proto_rawDesc
)

func file_alert_channel_proto_rawDescGZIP() []byte {
	file_alert_channel_proto_rawDescOnce.Do(func() {
		file_alert_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_channel_proto_rawDescData)
	})
	return file_alert_channel_proto_rawDescData
}

var file_alert_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alert_channel_proto_goTypes = []interface{}{
	(*AlertChannelRequest)(nil), // 0: alert.AlertChannelRequest
}
var file_alert_channel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_channel_proto_init() }
func file_alert_channel_proto_init() {
	if File_alert_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_channel_proto_goTypes,
		DependencyIndexes: file_alert_channel_proto_depIdxs,
		MessageInfos:      file_alert_channel_proto_msgTypes,
	}.Build()
	File_alert_channel_proto = out.File
	file_alert_channel_proto_rawDesc = nil
	file_alert_channel_proto_goTypes = nil
	file_alert_channel_proto_depIdxs = nil
}
