// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_strategy.proto

package alert_strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrategyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyName   string         `protobuf:"bytes,1,opt,name=strategyName,proto3" json:"strategyName" form:"strategyName" query:"strategyName"`
	StrategyDesc   string         `protobuf:"bytes,2,opt,name=strategyDesc,proto3" json:"strategyDesc" form:"strategyDesc" query:"strategyDesc"`
	Delay          int64          `protobuf:"varint,3,opt,name=delay,proto3" json:"delay" form:"delay" query:"delay"`
	TemplateId     uint64         `protobuf:"varint,4,opt,name=templateId,proto3" json:"templateId" form:"templateId" query:"templateId"`
	TimeSlot       *TimeSlot      `protobuf:"bytes,5,opt,name=timeSlot,proto3" json:"timeSlot" form:"timeSlot" query:"timeSlot"`
	Filters        []*Filters     `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters" form:"filters" query:"filters"`
	StrategySet    []*StrategySet `protobuf:"bytes,7,rep,name=strategySet,proto3" json:"strategySet" form:"strategySet" query:"strategySet"`
	WorkspaceId    uint64         `protobuf:"varint,8,opt,name=workspaceId,proto3" json:"workspaceId" form:"workspaceId" query:"workspaceId"`
	SystemStrategy *bool          `protobuf:"varint,9,opt,name=systemStrategy,proto3,oneof" json:"systemStrategy" form:"systemStrategy" query:"systemStrategy"`
	Continuous     *bool          `protobuf:"varint,10,opt,name=continuous,proto3,oneof" json:"continuous" form:"continuous" query:"continuous"`
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *StrategyRequest) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *StrategyRequest) GetStrategyDesc() string {
	if x != nil {
		return x.StrategyDesc
	}
	return ""
}

func (x *StrategyRequest) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *StrategyRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *StrategyRequest) GetTimeSlot() *TimeSlot {
	if x != nil {
		return x.TimeSlot
	}
	return nil
}

func (x *StrategyRequest) GetFilters() []*Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *StrategyRequest) GetStrategySet() []*StrategySet {
	if x != nil {
		return x.StrategySet
	}
	return nil
}

func (x *StrategyRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *StrategyRequest) GetSystemStrategy() bool {
	if x != nil && x.SystemStrategy != nil {
		return *x.SystemStrategy
	}
	return false
}

func (x *StrategyRequest) GetContinuous() bool {
	if x != nil && x.Continuous != nil {
		return *x.Continuous
	}
	return false
}

type Filters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*StrategyFilter `protobuf:"bytes,1,rep,name=values,proto3" json:"values" form:"values" query:"values"`
}

func (x *Filters) Reset() {
	*x = Filters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *Filters) GetValues() []*StrategyFilter {
	if x != nil {
		return x.Values
	}
	return nil
}

type SystemStrategyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyName string         `protobuf:"bytes,1,opt,name=strategyName,proto3" json:"strategyName" form:"strategyName" query:"strategyName"`
	StrategyDesc string         `protobuf:"bytes,2,opt,name=strategyDesc,proto3" json:"strategyDesc" form:"strategyDesc" query:"strategyDesc"`
	Delay        int64          `protobuf:"varint,3,opt,name=delay,proto3" json:"delay" form:"delay" query:"delay"`
	TemplateId   uint64         `protobuf:"varint,4,opt,name=templateId,proto3" json:"templateId" form:"templateId" query:"templateId"`
	StrategySet  []*StrategySet `protobuf:"bytes,7,rep,name=strategySet,proto3" json:"strategySet" form:"strategySet" query:"strategySet"`
}

func (x *SystemStrategyRequest) Reset() {
	*x = SystemStrategyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStrategyRequest) ProtoMessage() {}

func (x *SystemStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStrategyRequest.ProtoReflect.Descriptor instead.
func (*SystemStrategyRequest) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *SystemStrategyRequest) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *SystemStrategyRequest) GetStrategyDesc() string {
	if x != nil {
		return x.StrategyDesc
	}
	return ""
}

func (x *SystemStrategyRequest) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *SystemStrategyRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SystemStrategyRequest) GetStrategySet() []*StrategySet {
	if x != nil {
		return x.StrategySet
	}
	return nil
}

type SystemStrategyQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyName *string `protobuf:"bytes,1,opt,name=strategyName,proto3,oneof" json:"strategyName" form:"strategyName" query:"strategyName"`
	Page         uint64  `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page" query:"page"`
	PageSize     uint64  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize" form:"pageSize" query:"pageSize"`
}

func (x *SystemStrategyQuery) Reset() {
	*x = SystemStrategyQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStrategyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStrategyQuery) ProtoMessage() {}

func (x *SystemStrategyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStrategyQuery.ProtoReflect.Descriptor instead.
func (*SystemStrategyQuery) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStrategyQuery) GetStrategyName() string {
	if x != nil && x.StrategyName != nil {
		return *x.StrategyName
	}
	return ""
}

func (x *SystemStrategyQuery) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SystemStrategyQuery) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TimeSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable" form:"enable" query:"enable"`
	Type     *string  `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type" form:"type" query:"type"`
	Weeks    []int64  `protobuf:"varint,3,rep,packed,name=weeks,proto3" json:"weeks" form:"weeks" query:"weeks"`
	Times    []string `protobuf:"bytes,4,rep,name=times,proto3" json:"times" form:"times" query:"times"`
	Calendar *int64   `protobuf:"varint,5,opt,name=calendar,proto3,oneof" json:"calendar" form:"calendar" query:"calendar"`
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSlot) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *TimeSlot) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *TimeSlot) GetWeeks() []int64 {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *TimeSlot) GetTimes() []string {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *TimeSlot) GetCalendar() int64 {
	if x != nil && x.Calendar != nil {
		return *x.Calendar
	}
	return 0
}

type StrategyFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag" form:"tag" query:"tag"`
	Operation string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation" form:"operation" query:"operation"`
	Value     []string `protobuf:"bytes,3,rep,name=value,proto3" json:"value" form:"value" query:"value"`
}

func (x *StrategyFilter) Reset() {
	*x = StrategyFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyFilter) ProtoMessage() {}

func (x *StrategyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyFilter.ProtoReflect.Descriptor instead.
func (*StrategyFilter) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *StrategyFilter) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *StrategyFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StrategyFilter) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type StrategySet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members       []int64               `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members" form:"members" query:"members"`
	Teams         []int64               `protobuf:"varint,2,rep,packed,name=teams,proto3" json:"teams" form:"teams" query:"teams"`
	Schedules     []int64               `protobuf:"varint,3,rep,packed,name=schedules,proto3" json:"schedules" form:"schedules" query:"schedules"`
	AlertChannels []*structpb.ListValue `protobuf:"bytes,4,rep,name=alertChannels,proto3" json:"alertChannels" form:"alertChannels" query:"alertChannels"`
	AlertLoop     *AlertLoop            `protobuf:"bytes,6,opt,name=alertLoop,proto3,oneof" json:"alertLoop" form:"alertLoop" query:"alertLoop"`
	Progression   *Progression          `protobuf:"bytes,7,opt,name=progression,proto3,oneof" json:"progression" form:"progression" query:"progression"`
}

func (x *StrategySet) Reset() {
	*x = StrategySet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategySet) ProtoMessage() {}

func (x *StrategySet) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategySet.ProtoReflect.Descriptor instead.
func (*StrategySet) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *StrategySet) GetMembers() []int64 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *StrategySet) GetTeams() []int64 {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *StrategySet) GetSchedules() []int64 {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *StrategySet) GetAlertChannels() []*structpb.ListValue {
	if x != nil {
		return x.AlertChannels
	}
	return nil
}

func (x *StrategySet) GetAlertLoop() *AlertLoop {
	if x != nil {
		return x.AlertLoop
	}
	return nil
}

func (x *StrategySet) GetProgression() *Progression {
	if x != nil {
		return x.Progression
	}
	return nil
}

type AlertLoop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool  `protobuf:"varint,1,opt,name=enable,proto3" json:"enable" form:"enable" query:"enable"`
	Interval int64 `protobuf:"varint,2,opt,name=interval,proto3" json:"interval" form:"interval" query:"interval"`
	Count    int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count" form:"count" query:"count"`
}

func (x *AlertLoop) Reset() {
	*x = AlertLoop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertLoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertLoop) ProtoMessage() {}

func (x *AlertLoop) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertLoop.ProtoReflect.Descriptor instead.
func (*AlertLoop) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *AlertLoop) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *AlertLoop) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *AlertLoop) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Progression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable    bool  `protobuf:"varint,1,opt,name=enable,proto3" json:"enable" form:"enable" query:"enable"`
	Condition int64 `protobuf:"varint,2,opt,name=condition,proto3" json:"condition" form:"condition" query:"condition"`
	Duration  int64 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration" form:"duration" query:"duration"`
}

func (x *Progression) Reset() {
	*x = Progression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Progression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progression) ProtoMessage() {}

func (x *Progression) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progression.ProtoReflect.Descriptor instead.
func (*Progression) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *Progression) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Progression) GetCondition() int64 {
	if x != nil {
		return x.Condition
	}
	return 0
}

func (x *Progression) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ChangeStrategySort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id" query:"id"`
	Weight int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight" form:"weight" query:"weight"`
}

func (x *ChangeStrategySort) Reset() {
	*x = ChangeStrategySort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeStrategySort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStrategySort) ProtoMessage() {}

func (x *ChangeStrategySort) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStrategySort.ProtoReflect.Descriptor instead.
func (*ChangeStrategySort) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeStrategySort) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeStrategySort) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ChangeStrategySortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewWeight []*ChangeStrategySort `protobuf:"bytes,1,rep,name=newWeight,proto3" json:"newWeight" form:"newWeight" query:"newWeight"`
}

func (x *ChangeStrategySortRequest) Reset() {
	*x = ChangeStrategySortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_strategy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeStrategySortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStrategySortRequest) ProtoMessage() {}

func (x *ChangeStrategySortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_strategy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStrategySortRequest.ProtoReflect.Descriptor instead.
func (*ChangeStrategySortRequest) Descriptor() ([]byte, []int) {
	return file_alert_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeStrategySortRequest) GetNewWeight() []*ChangeStrategySort {
	if x != nil {
		return x.NewWeight
	}
	return nil
}

var File_alert_strategy_proto protoreflect.FileDescriptor

var file_alert_strategy_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x03, 0x0a, 0x0f,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x44,
	0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a,
	0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x53, 0x65, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0e,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x11,
	0x0a, 0x0f, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73,
	0x22, 0x38, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65,
	0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x74, 0x22, 0x7f, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x27, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x17,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x22, 0x56, 0x0a, 0x0e, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xab, 0x02, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x74, 0x65, 0x61,
	0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x40, 0x0a, 0x0d, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0d, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x09, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x4c, 0x6f, 0x6f, 0x70, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x48, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x6f, 0x6f, 0x70,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x55, 0x0a, 0x09, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5f, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x54, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x20, 0x5a, 0x1e,
	0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_strategy_proto_rawDescOnce sync.Once
	file_alert_strategy_proto_rawDescData = file_alert_strategy_proto_rawDesc
)

func file_alert_strategy_proto_rawDescGZIP() []byte {
	file_alert_strategy_proto_rawDescOnce.Do(func() {
		file_alert_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_strategy_proto_rawDescData)
	})
	return file_alert_strategy_proto_rawDescData
}

var file_alert_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_alert_strategy_proto_goTypes = []interface{}{
	(*StrategyRequest)(nil),           // 0: alert.StrategyRequest
	(*Filters)(nil),                   // 1: alert.Filters
	(*SystemStrategyRequest)(nil),     // 2: alert.SystemStrategyRequest
	(*SystemStrategyQuery)(nil),       // 3: alert.SystemStrategyQuery
	(*TimeSlot)(nil),                  // 4: alert.TimeSlot
	(*StrategyFilter)(nil),            // 5: alert.StrategyFilter
	(*StrategySet)(nil),               // 6: alert.StrategySet
	(*AlertLoop)(nil),                 // 7: alert.AlertLoop
	(*Progression)(nil),               // 8: alert.Progression
	(*ChangeStrategySort)(nil),        // 9: alert.ChangeStrategySort
	(*ChangeStrategySortRequest)(nil), // 10: alert.ChangeStrategySortRequest
	(*structpb.ListValue)(nil),        // 11: google.protobuf.ListValue
}
var file_alert_strategy_proto_depIdxs = []int32{
	4,  // 0: alert.StrategyRequest.timeSlot:type_name -> alert.TimeSlot
	1,  // 1: alert.StrategyRequest.filters:type_name -> alert.Filters
	6,  // 2: alert.StrategyRequest.strategySet:type_name -> alert.StrategySet
	5,  // 3: alert.Filters.values:type_name -> alert.StrategyFilter
	6,  // 4: alert.SystemStrategyRequest.strategySet:type_name -> alert.StrategySet
	11, // 5: alert.StrategySet.alertChannels:type_name -> google.protobuf.ListValue
	7,  // 6: alert.StrategySet.alertLoop:type_name -> alert.AlertLoop
	8,  // 7: alert.StrategySet.progression:type_name -> alert.Progression
	9,  // 8: alert.ChangeStrategySortRequest.newWeight:type_name -> alert.ChangeStrategySort
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_alert_strategy_proto_init() }
func file_alert_strategy_proto_init() {
	if File_alert_strategy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_strategy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStrategyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStrategyQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategySet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertLoop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Progression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeStrategySort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_strategy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeStrategySortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_alert_strategy_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_alert_strategy_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_alert_strategy_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_alert_strategy_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_strategy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_strategy_proto_goTypes,
		DependencyIndexes: file_alert_strategy_proto_depIdxs,
		MessageInfos:      file_alert_strategy_proto_msgTypes,
	}.Build()
	File_alert_strategy_proto = out.File
	file_alert_strategy_proto_rawDesc = nil
	file_alert_strategy_proto_goTypes = nil
	file_alert_strategy_proto_depIdxs = nil
}
