// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_silence.proto

package alert_silence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SilenceTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RangeTime []string `protobuf:"bytes,1,rep,name=rangeTime,proto3" json:"rangeTime" form:"rangeTime" query:"rangeTime"`
	Weeks     []int64  `protobuf:"varint,2,rep,packed,name=weeks,proto3" json:"weeks" form:"weeks" query:"weeks"`
	Times     []string `protobuf:"bytes,3,rep,name=times,proto3" json:"times" form:"times" query:"times"`
}

func (x *SilenceTime) Reset() {
	*x = SilenceTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_silence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SilenceTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceTime) ProtoMessage() {}

func (x *SilenceTime) ProtoReflect() protoreflect.Message {
	mi := &file_alert_silence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceTime.ProtoReflect.Descriptor instead.
func (*SilenceTime) Descriptor() ([]byte, []int) {
	return file_alert_silence_proto_rawDescGZIP(), []int{0}
}

func (x *SilenceTime) GetRangeTime() []string {
	if x != nil {
		return x.RangeTime
	}
	return nil
}

func (x *SilenceTime) GetWeeks() []int64 {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *SilenceTime) GetTimes() []string {
	if x != nil {
		return x.Times
	}
	return nil
}

type SilenceFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag" form:"tag" query:"tag"`
	Operation string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation" form:"operation" query:"operation"`
	Value     []string `protobuf:"bytes,3,rep,name=value,proto3" json:"value" form:"value" query:"value"`
}

func (x *SilenceFilter) Reset() {
	*x = SilenceFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_silence_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SilenceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceFilter) ProtoMessage() {}

func (x *SilenceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alert_silence_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceFilter.ProtoReflect.Descriptor instead.
func (*SilenceFilter) Descriptor() ([]byte, []int) {
	return file_alert_silence_proto_rawDescGZIP(), []int{1}
}

func (x *SilenceFilter) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SilenceFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SilenceFilter) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type SilenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SilenceName string           `protobuf:"bytes,1,opt,name=silenceName,proto3" json:"silenceName" form:"silenceName" query:"silenceName"`
	SilenceDesc string           `protobuf:"bytes,2,opt,name=silenceDesc,proto3" json:"silenceDesc" form:"silenceDesc" query:"silenceDesc"`
	SilenceType string           `protobuf:"bytes,3,opt,name=silenceType,proto3" json:"silenceType" form:"silenceType" query:"silenceType"`
	TemplateId  uint64           `protobuf:"varint,4,opt,name=templateId,proto3" json:"templateId" form:"templateId" query:"templateId"`
	SilenceTime *SilenceTime     `protobuf:"bytes,5,opt,name=silenceTime,proto3" json:"silenceTime" form:"silenceTime" query:"silenceTime"`
	Filters     []*SilenceFilter `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters" form:"filters" query:"filters"`
	WorkspaceId uint64           `protobuf:"varint,8,opt,name=workspaceId,proto3" json:"workspaceId" form:"workspaceId" query:"workspaceId"`
}

func (x *SilenceRequest) Reset() {
	*x = SilenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_silence_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SilenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceRequest) ProtoMessage() {}

func (x *SilenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_silence_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceRequest.ProtoReflect.Descriptor instead.
func (*SilenceRequest) Descriptor() ([]byte, []int) {
	return file_alert_silence_proto_rawDescGZIP(), []int{2}
}

func (x *SilenceRequest) GetSilenceName() string {
	if x != nil {
		return x.SilenceName
	}
	return ""
}

func (x *SilenceRequest) GetSilenceDesc() string {
	if x != nil {
		return x.SilenceDesc
	}
	return ""
}

func (x *SilenceRequest) GetSilenceType() string {
	if x != nil {
		return x.SilenceType
	}
	return ""
}

func (x *SilenceRequest) GetTemplateId() uint64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *SilenceRequest) GetSilenceTime() *SilenceTime {
	if x != nil {
		return x.SilenceTime
	}
	return nil
}

func (x *SilenceRequest) GetFilters() []*SilenceFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SilenceRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

var File_alert_silence_proto protoreflect.FileDescriptor

var file_alert_silence_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x57, 0x0a, 0x0b,
	0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x65,
	0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x77, 0x65, 0x65, 0x6b, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x55, 0x0a, 0x0d, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9e, 0x02, 0x0a,
	0x0e, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2e, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x0b,
	0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x2e, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x42, 0x1f, 0x5a,
	0x1d, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_silence_proto_rawDescOnce sync.Once
	file_alert_silence_proto_rawDescData = file_alert_silence_proto_rawDesc
)

func file_alert_silence_proto_rawDescGZIP() []byte {
	file_alert_silence_proto_rawDescOnce.Do(func() {
		file_alert_silence_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_silence_proto_rawDescData)
	})
	return file_alert_silence_proto_rawDescData
}

var file_alert_silence_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alert_silence_proto_goTypes = []interface{}{
	(*SilenceTime)(nil),    // 0: alert.SilenceTime
	(*SilenceFilter)(nil),  // 1: alert.SilenceFilter
	(*SilenceRequest)(nil), // 2: alert.SilenceRequest
}
var file_alert_silence_proto_depIdxs = []int32{
	0, // 0: alert.SilenceRequest.silenceTime:type_name -> alert.SilenceTime
	1, // 1: alert.SilenceRequest.filters:type_name -> alert.SilenceFilter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_silence_proto_init() }
func file_alert_silence_proto_init() {
	if File_alert_silence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_silence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SilenceTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_silence_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SilenceFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_silence_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SilenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_silence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_silence_proto_goTypes,
		DependencyIndexes: file_alert_silence_proto_depIdxs,
		MessageInfos:      file_alert_silence_proto_msgTypes,
	}.Build()
	File_alert_silence_proto = out.File
	file_alert_silence_proto_rawDesc = nil
	file_alert_silence_proto_goTypes = nil
	file_alert_silence_proto_depIdxs = nil
}
