// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert-rule-source.proto

package alert_rule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceName string `protobuf:"bytes,1,opt,name=sourceName,proto3" json:"sourceName" form:"sourceName" query:"sourceName"`
	SourceType string `protobuf:"bytes,2,opt,name=sourceType,proto3" json:"sourceType" form:"sourceType" query:"sourceType"`
	Mark       string `protobuf:"bytes,3,opt,name=mark,proto3" json:"mark" form:"mark" query:"mark"`
	Address    string `protobuf:"bytes,4,opt,name=address,proto3" json:"address" form:"address" query:"address"`
	Sign       string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign" form:"sign" query:"sign"`
}

func (x *SourceRequest) Reset() {
	*x = SourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_rule_source_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRequest) ProtoMessage() {}

func (x *SourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_rule_source_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRequest.ProtoReflect.Descriptor instead.
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return file_alert_rule_source_proto_rawDescGZIP(), []int{0}
}

func (x *SourceRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SourceRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *SourceRequest) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *SourceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SourceRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_alert_rule_source_proto protoreflect.FileDescriptor

var file_alert_rule_source_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2d, 0x72, 0x75, 0x6c, 0x65, 0x2d, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x5f, 0x72, 0x75, 0x6c, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x69, 0x6e,
	0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_rule_source_proto_rawDescOnce sync.Once
	file_alert_rule_source_proto_rawDescData = file_alert_rule_source_proto_rawDesc
)

func file_alert_rule_source_proto_rawDescGZIP() []byte {
	file_alert_rule_source_proto_rawDescOnce.Do(func() {
		file_alert_rule_source_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_rule_source_proto_rawDescData)
	})
	return file_alert_rule_source_proto_rawDescData
}

var file_alert_rule_source_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alert_rule_source_proto_goTypes = []interface{}{
	(*SourceRequest)(nil), // 0: alert_rule.SourceRequest
}
var file_alert_rule_source_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_rule_source_proto_init() }
func file_alert_rule_source_proto_init() {
	if File_alert_rule_source_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_rule_source_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_rule_source_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_rule_source_proto_goTypes,
		DependencyIndexes: file_alert_rule_source_proto_depIdxs,
		MessageInfos:      file_alert_rule_source_proto_msgTypes,
	}.Build()
	File_alert_rule_source_proto = out.File
	file_alert_rule_source_proto_rawDesc = nil
	file_alert_rule_source_proto_goTypes = nil
	file_alert_rule_source_proto_depIdxs = nil
}
