// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_rule.proto

package alert_rule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName  string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName" form:"groupName" query:"groupName"`
	RuleSource uint64 `protobuf:"varint,2,opt,name=ruleSource,proto3" json:"ruleSource" form:"ruleSource" query:"ruleSource"`
	File       string `protobuf:"bytes,3,opt,name=file,proto3" json:"file" form:"file" query:"file"`
}

func (x *RuleGroupRequest) Reset() {
	*x = RuleGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleGroupRequest) ProtoMessage() {}

func (x *RuleGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleGroupRequest.ProtoReflect.Descriptor instead.
func (*RuleGroupRequest) Descriptor() ([]byte, []int) {
	return file_alert_rule_proto_rawDescGZIP(), []int{0}
}

func (x *RuleGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *RuleGroupRequest) GetRuleSource() uint64 {
	if x != nil {
		return x.RuleSource
	}
	return 0
}

func (x *RuleGroupRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type RuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name" query:"name"`
	Gid        uint64       `protobuf:"varint,2,opt,name=gid,proto3" json:"gid" form:"gid" query:"gid"`
	Query      string       `protobuf:"bytes,3,opt,name=query,proto3" json:"query" form:"query" query:"query"`
	Duration   int64        `protobuf:"varint,4,opt,name=duration,proto3" json:"duration" form:"duration" query:"duration"`
	Labels     []*RuleLabel `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels" form:"labels" query:"labels"`
	Annotation []*RuleLabel `protobuf:"bytes,6,rep,name=annotation,proto3" json:"annotation" form:"annotation" query:"annotation"`
}

func (x *RuleRequest) Reset() {
	*x = RuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_rule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleRequest) ProtoMessage() {}

func (x *RuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_rule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleRequest.ProtoReflect.Descriptor instead.
func (*RuleRequest) Descriptor() ([]byte, []int) {
	return file_alert_rule_proto_rawDescGZIP(), []int{1}
}

func (x *RuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleRequest) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *RuleRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RuleRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RuleRequest) GetLabels() []*RuleLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RuleRequest) GetAnnotation() []*RuleLabel {
	if x != nil {
		return x.Annotation
	}
	return nil
}

type RuleLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag" form:"tag" query:"tag"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value" form:"value" query:"value"`
}

func (x *RuleLabel) Reset() {
	*x = RuleLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_rule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleLabel) ProtoMessage() {}

func (x *RuleLabel) ProtoReflect() protoreflect.Message {
	mi := &file_alert_rule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleLabel.ProtoReflect.Descriptor instead.
func (*RuleLabel) Descriptor() ([]byte, []int) {
	return file_alert_rule_proto_rawDescGZIP(), []int{2}
}

func (x *RuleLabel) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RuleLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_alert_rule_proto protoreflect.FileDescriptor

var file_alert_rule_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x22, 0x64,
	0x0a, 0x10, 0x52, 0x75, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x0b, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x75, 0x6c,
	0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x09, 0x52, 0x75, 0x6c, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x69, 0x6e, 0x6f, 0x73,
	0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x5f, 0x72, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_rule_proto_rawDescOnce sync.Once
	file_alert_rule_proto_rawDescData = file_alert_rule_proto_rawDesc
)

func file_alert_rule_proto_rawDescGZIP() []byte {
	file_alert_rule_proto_rawDescOnce.Do(func() {
		file_alert_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_rule_proto_rawDescData)
	})
	return file_alert_rule_proto_rawDescData
}

var file_alert_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alert_rule_proto_goTypes = []interface{}{
	(*RuleGroupRequest)(nil), // 0: alert_rule.RuleGroupRequest
	(*RuleRequest)(nil),      // 1: alert_rule.RuleRequest
	(*RuleLabel)(nil),        // 2: alert_rule.RuleLabel
}
var file_alert_rule_proto_depIdxs = []int32{
	2, // 0: alert_rule.RuleRequest.labels:type_name -> alert_rule.RuleLabel
	2, // 1: alert_rule.RuleRequest.annotation:type_name -> alert_rule.RuleLabel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_rule_proto_init() }
func file_alert_rule_proto_init() {
	if File_alert_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_rule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_rule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_rule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_rule_proto_goTypes,
		DependencyIndexes: file_alert_rule_proto_depIdxs,
		MessageInfos:      file_alert_rule_proto_msgTypes,
	}.Build()
	File_alert_rule_proto = out.File
	file_alert_rule_proto_rawDesc = nil
	file_alert_rule_proto_goTypes = nil
	file_alert_rule_proto_depIdxs = nil
}
