// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_evnet.proto

package alert_event

import (
	_ "darkhawk/hertz_gen/api"
	base "darkhawk/hertz_gen/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceEventListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertTitle string `protobuf:"bytes,1,opt,name=alertTitle,proto3" json:"alertTitle" form:"alertTitle" query:"alertTitle"`
	Progress   uint32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress" form:"progress" query:"progress"`
	TimeRange  string `protobuf:"bytes,3,opt,name=timeRange,proto3" json:"timeRange" form:"timeRange" query:"timeRange"`
	AlertLevel *int64 `protobuf:"varint,4,opt,name=alertLevel,proto3,oneof" json:"alertLevel" form:"alertLevel" query:"alertLevel"`
	Page       uint64 `protobuf:"varint,5,opt,name=page,proto3" json:"page" form:"page" query:"page"`
	PageSize   uint64 `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize" form:"pageSize" query:"pageSize"`
}

func (x *WorkspaceEventListRequest) Reset() {
	*x = WorkspaceEventListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_evnet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceEventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceEventListRequest) ProtoMessage() {}

func (x *WorkspaceEventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_evnet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceEventListRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceEventListRequest) Descriptor() ([]byte, []int) {
	return file_alert_evnet_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceEventListRequest) GetAlertTitle() string {
	if x != nil {
		return x.AlertTitle
	}
	return ""
}

func (x *WorkspaceEventListRequest) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *WorkspaceEventListRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *WorkspaceEventListRequest) GetAlertLevel() int64 {
	if x != nil && x.AlertLevel != nil {
		return *x.AlertLevel
	}
	return 0
}

func (x *WorkspaceEventListRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *WorkspaceEventListRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ClaimEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []uint64 `protobuf:"varint,1,rep,packed,name=events,proto3" json:"events" form:"events" query:"events"`
}

func (x *ClaimEventRequest) Reset() {
	*x = ClaimEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_evnet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimEventRequest) ProtoMessage() {}

func (x *ClaimEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_evnet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimEventRequest.ProtoReflect.Descriptor instead.
func (*ClaimEventRequest) Descriptor() ([]byte, []int) {
	return file_alert_evnet_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimEventRequest) GetEvents() []uint64 {
	if x != nil {
		return x.Events
	}
	return nil
}

type CloseEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events      []uint64 `protobuf:"varint,1,rep,packed,name=events,proto3" json:"events" form:"events" query:"events"`
	IsRecovered bool     `protobuf:"varint,2,opt,name=isRecovered,proto3" json:"isRecovered" form:"isRecovered" query:"isRecovered"`
}

func (x *CloseEventRequest) Reset() {
	*x = CloseEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_evnet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEventRequest) ProtoMessage() {}

func (x *CloseEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_evnet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEventRequest.ProtoReflect.Descriptor instead.
func (*CloseEventRequest) Descriptor() ([]byte, []int) {
	return file_alert_evnet_proto_rawDescGZIP(), []int{2}
}

func (x *CloseEventRequest) GetEvents() []uint64 {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *CloseEventRequest) GetIsRecovered() bool {
	if x != nil {
		return x.IsRecovered
	}
	return false
}

var File_alert_evnet_proto protoreflect.FileDescriptor

var file_alert_evnet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x65, 0x76, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x19, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x0a, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x2b, 0x0a,
	0x11, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x32, 0x81, 0x01, 0x0a, 0x11, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6c, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0xca, 0xc1, 0x18,
	0x1c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x1d, 0x5a,
	0x1b, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_evnet_proto_rawDescOnce sync.Once
	file_alert_evnet_proto_rawDescData = file_alert_evnet_proto_rawDesc
)

func file_alert_evnet_proto_rawDescGZIP() []byte {
	file_alert_evnet_proto_rawDescOnce.Do(func() {
		file_alert_evnet_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_evnet_proto_rawDescData)
	})
	return file_alert_evnet_proto_rawDescData
}

var file_alert_evnet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alert_evnet_proto_goTypes = []interface{}{
	(*WorkspaceEventListRequest)(nil), // 0: alert.WorkspaceEventListRequest
	(*ClaimEventRequest)(nil),         // 1: alert.ClaimEventRequest
	(*CloseEventRequest)(nil),         // 2: alert.CloseEventRequest
	(*base.BaseListResp)(nil),         // 3: base.BaseListResp
}
var file_alert_evnet_proto_depIdxs = []int32{
	0, // 0: alert.AlertEventService.WorkspaceEventList:input_type -> alert.WorkspaceEventListRequest
	3, // 1: alert.AlertEventService.WorkspaceEventList:output_type -> base.BaseListResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alert_evnet_proto_init() }
func file_alert_evnet_proto_init() {
	if File_alert_evnet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_evnet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceEventListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_evnet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_evnet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_alert_evnet_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_evnet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_evnet_proto_goTypes,
		DependencyIndexes: file_alert_evnet_proto_depIdxs,
		MessageInfos:      file_alert_evnet_proto_msgTypes,
	}.Build()
	File_alert_evnet_proto = out.File
	file_alert_evnet_proto_rawDesc = nil
	file_alert_evnet_proto_goTypes = nil
	file_alert_evnet_proto_depIdxs = nil
}
