// Code generated by Kitex v0.5.1. DO NOT EDIT.

package userservice

import (
	"context"
	sso "minos/kitex_gen/sso"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserList(ctx context.Context, Req *sso.UserQuery, callOptions ...callopt.Option) (r *sso.UserListResp, err error)
	UserByUsername(ctx context.Context, Req *sso.GetUserReq, callOptions ...callopt.Option) (r *sso.UserInfo, err error)
	UserById(ctx context.Context, Req *sso.GetUserByIdReq, callOptions ...callopt.Option) (r *sso.UserInfo, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) UserList(ctx context.Context, Req *sso.UserQuery, callOptions ...callopt.Option) (r *sso.UserListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserList(ctx, Req)
}

func (p *kUserServiceClient) UserByUsername(ctx context.Context, Req *sso.GetUserReq, callOptions ...callopt.Option) (r *sso.UserInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserByUsername(ctx, Req)
}

func (p *kUserServiceClient) UserById(ctx context.Context, Req *sso.GetUserByIdReq, callOptions ...callopt.Option) (r *sso.UserInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserById(ctx, Req)
}
