package mysql

const (
	WorkspaceTable               = "workspace"
	WorkspaceTeamTable           = "workspace_team"
	WorkspaceSourceTable         = "workspace_source"
	SystemIntegrationTable       = "system_integration"
	IntegrationRouterTable       = "integration_router"
	TagRewriteTable              = "tag_rewrite"
	WorkspaceRouterTable         = "workspace_router"
	AlertTemplateTable           = "alert_template"
	ChannelTemplateTable         = "channel_template"
	LevelSourceMappingTable      = "level_source_mapping"
	LevelIntegrationMappingTable = "level_integration_mapping"
	AlertWorkspaceTable          = "alert_workspace"
	TeamsTable                   = "teams"
	TeamsRuleTable               = "team_rule"
	MenuTable                    = "menu"
	UserTable                    = "user"
	TeamUserTable                = "user_teams"
	AlertLevelTable              = "alert_level"
	AlertRuleTable               = "alert_rule"
	AlertRuleSourceTable         = "alert_rule_source"
	AlertRuleGroupTable          = "alert_rule_group"
	AlertChannelTable            = "alert_channel"
	AlertWebhookTable            = "webhooks"
	AlertEventTable              = "alert_event"
	AlertSourceTable             = "alert_source"
	ScheduleTable                = "schedule"
	SchedulePlanTable            = "schedule_plan"
	AlertStrategyTable           = "alert_strategy"
	StrategyLogTable             = "strategy_log"
	SystemStrategyTable          = "system_strategy"
	AlertSilenceTable            = "alert_silence"
	AlertRestrainTable           = "alert_restrain"
	AlertAggregationTable        = "alert_aggregation"
	AlertLog                     = "alert_log"
	Agents                       = "agents"
	SilenceLogTable              = "silence_log"
)
