// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: alert_aggregation.proto

package alert_aggregation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggregationName string        `protobuf:"bytes,1,opt,name=aggregationName,proto3" json:"aggregationName" form:"aggregationName" query:"aggregationName"`
	AggregationDesc string        `protobuf:"bytes,2,opt,name=aggregationDesc,proto3" json:"aggregationDesc" form:"aggregationDesc" query:"aggregationDesc"`
	WorkspaceId     uint64        `protobuf:"varint,3,opt,name=workspaceId,proto3" json:"workspaceId" form:"workspaceId" query:"workspaceId"`
	LevelDimension  bool          `protobuf:"varint,4,opt,name=levelDimension,proto3" json:"levelDimension" form:"levelDimension" query:"levelDimension"`
	TitleDimension  bool          `protobuf:"varint,5,opt,name=titleDimension,proto3" json:"titleDimension" form:"titleDimension" query:"titleDimension"`
	TagsDimension   []*TagFilters `protobuf:"bytes,6,rep,name=tagsDimension,proto3" json:"tagsDimension" form:"tagsDimension" query:"tagsDimension"`
	Windows         int64         `protobuf:"varint,7,opt,name=windows,proto3" json:"windows" form:"windows" query:"windows"`
	Storm           int64         `protobuf:"varint,8,opt,name=storm,proto3" json:"storm" form:"storm" query:"storm"`
}

func (x *AggregationRequest) Reset() {
	*x = AggregationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_aggregation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationRequest) ProtoMessage() {}

func (x *AggregationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_aggregation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationRequest.ProtoReflect.Descriptor instead.
func (*AggregationRequest) Descriptor() ([]byte, []int) {
	return file_alert_aggregation_proto_rawDescGZIP(), []int{0}
}

func (x *AggregationRequest) GetAggregationName() string {
	if x != nil {
		return x.AggregationName
	}
	return ""
}

func (x *AggregationRequest) GetAggregationDesc() string {
	if x != nil {
		return x.AggregationDesc
	}
	return ""
}

func (x *AggregationRequest) GetWorkspaceId() uint64 {
	if x != nil {
		return x.WorkspaceId
	}
	return 0
}

func (x *AggregationRequest) GetLevelDimension() bool {
	if x != nil {
		return x.LevelDimension
	}
	return false
}

func (x *AggregationRequest) GetTitleDimension() bool {
	if x != nil {
		return x.TitleDimension
	}
	return false
}

func (x *AggregationRequest) GetTagsDimension() []*TagFilters {
	if x != nil {
		return x.TagsDimension
	}
	return nil
}

func (x *AggregationRequest) GetWindows() int64 {
	if x != nil {
		return x.Windows
	}
	return 0
}

func (x *AggregationRequest) GetStorm() int64 {
	if x != nil {
		return x.Storm
	}
	return 0
}

type TagFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*TagFilter `protobuf:"bytes,1,rep,name=values,proto3" json:"values" form:"values" query:"values"`
}

func (x *TagFilters) Reset() {
	*x = TagFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_aggregation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilters) ProtoMessage() {}

func (x *TagFilters) ProtoReflect() protoreflect.Message {
	mi := &file_alert_aggregation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilters.ProtoReflect.Descriptor instead.
func (*TagFilters) Descriptor() ([]byte, []int) {
	return file_alert_aggregation_proto_rawDescGZIP(), []int{1}
}

func (x *TagFilters) GetValues() []*TagFilter {
	if x != nil {
		return x.Values
	}
	return nil
}

type TagFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag" form:"tag" query:"tag"`
	Operation string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation" form:"operation" query:"operation"`
	Value     []string `protobuf:"bytes,3,rep,name=value,proto3" json:"value" form:"value" query:"value"`
}

func (x *TagFilter) Reset() {
	*x = TagFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_aggregation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilter) ProtoMessage() {}

func (x *TagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_alert_aggregation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilter.ProtoReflect.Descriptor instead.
func (*TagFilter) Descriptor() ([]byte, []int) {
	return file_alert_aggregation_proto_rawDescGZIP(), []int{2}
}

func (x *TagFilter) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TagFilter) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_alert_aggregation_proto protoreflect.FileDescriptor

var file_alert_aggregation_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x22, 0xc3, 0x02, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x67, 0x67, 0x72,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x44, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a,
	0x0d, 0x74, 0x61, 0x67, 0x73, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x54, 0x61, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0d, 0x74, 0x61, 0x67, 0x73, 0x44, 0x69, 0x6d,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x22, 0x36, 0x0a, 0x0a, 0x54, 0x61, 0x67, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x54, 0x61, 0x67,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x51,
	0x0a, 0x09, 0x54, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x23, 0x5a, 0x21, 0x6d, 0x69, 0x6e, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x67, 0x67, 0x72, 0x65,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_aggregation_proto_rawDescOnce sync.Once
	file_alert_aggregation_proto_rawDescData = file_alert_aggregation_proto_rawDesc
)

func file_alert_aggregation_proto_rawDescGZIP() []byte {
	file_alert_aggregation_proto_rawDescOnce.Do(func() {
		file_alert_aggregation_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_aggregation_proto_rawDescData)
	})
	return file_alert_aggregation_proto_rawDescData
}

var file_alert_aggregation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alert_aggregation_proto_goTypes = []interface{}{
	(*AggregationRequest)(nil), // 0: alert.AggregationRequest
	(*TagFilters)(nil),         // 1: alert.TagFilters
	(*TagFilter)(nil),          // 2: alert.TagFilter
}
var file_alert_aggregation_proto_depIdxs = []int32{
	1, // 0: alert.AggregationRequest.tagsDimension:type_name -> alert.TagFilters
	2, // 1: alert.TagFilters.values:type_name -> alert.TagFilter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_aggregation_proto_init() }
func file_alert_aggregation_proto_init() {
	if File_alert_aggregation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_aggregation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_aggregation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_aggregation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_aggregation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_aggregation_proto_goTypes,
		DependencyIndexes: file_alert_aggregation_proto_depIdxs,
		MessageInfos:      file_alert_aggregation_proto_msgTypes,
	}.Build()
	File_alert_aggregation_proto = out.File
	file_alert_aggregation_proto_rawDesc = nil
	file_alert_aggregation_proto_goTypes = nil
	file_alert_aggregation_proto_depIdxs = nil
}
