// Code generated by Kitex v0.9.0. DO NOT EDIT.

package owlagentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	owl_agent "agent/kitex_gen/owl_agent"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UpdateRule": kitex.NewMethodInfo(
		updateRuleHandler,
		newUpdateRuleArgs,
		newUpdateRuleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	owlAgentServiceServiceInfo                = NewServiceInfo()
	owlAgentServiceServiceInfoForClient       = NewServiceInfoForClient()
	owlAgentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return owlAgentServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return owlAgentServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return owlAgentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OwlAgentService"
	handlerType := (*owl_agent.OwlAgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "owl_agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.0",
		Extra:           extra,
	}
	return svcInfo
}

func updateRuleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(owl_agent.RuleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(owl_agent.OwlAgentService).UpdateRule(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateRuleArgs:
		success, err := handler.(owl_agent.OwlAgentService).UpdateRule(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateRuleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateRuleArgs() interface{} {
	return &UpdateRuleArgs{}
}

func newUpdateRuleResult() interface{} {
	return &UpdateRuleResult{}
}

type UpdateRuleArgs struct {
	Req *owl_agent.RuleRequest
}

func (p *UpdateRuleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateRuleArgs) Unmarshal(in []byte) error {
	msg := new(owl_agent.RuleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateRuleArgs_Req_DEFAULT *owl_agent.RuleRequest

func (p *UpdateRuleArgs) GetReq() *owl_agent.RuleRequest {
	if !p.IsSetReq() {
		return UpdateRuleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateRuleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateRuleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateRuleResult struct {
	Success *emptypb.Empty
}

var UpdateRuleResult_Success_DEFAULT *emptypb.Empty

func (p *UpdateRuleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateRuleResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateRuleResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return UpdateRuleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateRuleResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *UpdateRuleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateRuleResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UpdateRule(ctx context.Context, Req *owl_agent.RuleRequest) (r *emptypb.Empty, err error) {
	var _args UpdateRuleArgs
	_args.Req = Req
	var _result UpdateRuleResult
	if err = p.c.Call(ctx, "UpdateRule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
